<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin-PC" name="TestNgClassTest" tests="36" failures="7" timestamp="8 Jul 2020 19:41:33 GMT" time="14.572" errors="0">
  <testcase name="f" time="0.014" classname="ItestListenerConcept.class1"/>
  <testcase name="Testcase" time="0.004" classname="TestcaseSquence.ExceptionTimeoutTest">
    <failure type="org.testng.TestException" message="
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Testcase -->
  <testcase name="Testcase" time="0.003" classname="TestcaseSquence.ExceptionTimeoutTest">
    <failure type="org.testng.TestException" message="
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Testcase -->
  <testcase name="Testcase" time="0.003" classname="TestcaseSquence.ExceptionTimeoutTest">
    <failure type="org.testng.TestException" message="
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Testcase -->
  <testcase name="Testcase" time="0.019" classname="TestcaseSquence.ExceptionTimeoutTest">
    <failure type="org.testng.TestException" message="
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Testcase -->
  <testcase name="Testcase" time="0.002" classname="TestcaseSquence.ExceptionTimeoutTest">
    <failure type="org.testng.TestException" message="
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method ExceptionTimeoutTest.Testcase()[pri:0, instance:TestcaseSquence.ExceptionTimeoutTest@3c09711b] should have thrown an exception of type class java.lang.NumberFormatException
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Testcase -->
  <testcase name="googleTileTest" time="0.075" classname="TestcaseSquence.GoogleTitleTest"/>
  <testcase name="testcase1" time="0.008" classname="TestcaseSquence.InvocationCount"/>
  <testcase name="testcase1" time="0.03" classname="TestcaseSquence.InvocationCount"/>
  <testcase name="testcase1" time="0.002" classname="TestcaseSquence.InvocationCount"/>
  <testcase name="testcase1" time="0.002" classname="TestcaseSquence.InvocationCount"/>
  <testcase name="testcase1" time="0.002" classname="TestcaseSquence.InvocationCount"/>
  <testcase name="testcase1" time="0.006" classname="TestcaseSquence.MyTestcase"/>
  <testcase name="testcase2" time="0.003" classname="TestcaseSquence.MyTestcase"/>
  <testcase name="TEST" time="0.003" classname="TestcaseSquence.NumberFormateException"/>
  <testcase name="login" time="0.003" classname="TestcaseSquence.SkipTestcase">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at TestcaseSquence.SkipTestcase.login(SkipTestcase.java:16)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="Logout" time="0.003" classname="TestcaseSquence.SkipTestcase"/>
  <testcase name="Home" time="0.0" classname="TestcaseSquence.SkipTestcase">
    <skipped/>
  </testcase> <!-- Home -->
  <testcase name="testcase1" time="0.003" classname="TestcaseSquence.TestcaseDependonMethods"/>
  <testcase name="testcase2" time="0.002" classname="TestcaseSquence.TestcaseDependonMethods"/>
  <testcase name="testcase3" time="0.006" classname="TestcaseSquence.TestcaseDependonMethods"/>
  <testcase name="testcase3" time="0.002" classname="TestcaseSquence.TestcaseGroup"/>
  <testcase name="testcase1" time="0.002" classname="TestcaseSquence.TestcaseGroup"/>
  <testcase name="testcase2" time="0.01" classname="TestcaseSquence.TestcaseGroup"/>
  <testcase name="testcase3" time="0.003" classname="TestcaseSquence.TestNGPriority"/>
  <testcase name="testcase1" time="0.002" classname="TestcaseSquence.TestNGPriority"/>
  <testcase name="testcase2" time="0.023" classname="TestcaseSquence.TestNGPriority"/>
  <testcase name="testcase1" time="0.002" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testcase2" time="0.002" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testcase3" time="0.001" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testcase4" time="0.001" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testcase5" time="0.002" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testcase6" time="0.012" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testcase7" time="0.002" classname="TestcaseSquence.TestSquence"/>
  <testcase name="testCaseOne" time="0.001" classname="com.parameterization.TestParameters">
    <failure type="org.testng.TestException" message="
Method TestParameters.testCaseOne(java.lang.String)[pri:0, instance:com.parameterization.TestParameters@5ae9a829] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method TestParameters.testCaseOne(java.lang.String)[pri:0, instance:com.parameterization.TestParameters@5ae9a829] should have thrown an exception of type class java.lang.NumberFormatException
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testCaseOne -->
  <testcase name="testCaseTwo" time="0.002" classname="com.parameterization.TestParameters"/>
</testsuite> <!-- TestNgClassTest -->
